### PR TITLE
Refactoring matlab tutorial

### PR DESCRIPTION
**Pull request by TimVanMourik**
Work in progress, so please don't merge yet. I'm refactoring block by block, commit by commit.

### CODE REVIEW

**Comment by KirstieJane** [comment]
:+1: Thanks @TimVanMourik!

**Comment by TimVanMourik** [comment]
@TomRhysMarshall, @KirstieJane 
So hereby the entire matlab tutorial has been refactored and remade to work for MATLAB 2015B. I haven't tested backwards compatibility for anything before that, but around that time the figure API was rewritten. I called the file `raincloud_plots_tutorial_2015B.m`. You may consider making new files that are compatible with other versions.
* I included the figures, but these may of course look different when made with different versions. I leave it up to you if you want to make subfolders for each version or just one with figures from the latest version.
* You might want to incorporate some refactorings in the up-to-date file. I leave that up to you.
* I'll have a look at the actual plotting code later in a new PR

**Comment by KirstieJane** [comment]
Awesome! Thanks @TimVanMourik!

@TomRhysMarshall - can you review this PR? I don't code in matlab so I don't think I'll be any use!!

Happy to chime in on any  of the stylistic changes once you (Tom) have had a look and shared your opinion 😸

**Comment by TomRhysMarshall** [comment]
image

**Comment by TimVanMourik** [comment]
I strongly recommend the [GitHub Desktop app](https://desktop.github.com):
untitled

And just going through the commits one by one at all the changes:

untitled

**Pull request merged**
