### PR TITLE
Restructuring repository (WIP)

### PR DESCRIPTION
**Pull request by TimVanMourik**
This is a suggestion for slightly rearranging the repository's structure, as mentioned in #7.

It is still work in progress as the code has not been updated to refer to the new location of the data files. I will do this for MATLAB but not for Python and R.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Thanks @TimVanMourik! I've left a comment in #7.

Just a heads up that I won't be able to merge this until all the tutorials work, so I'm not sure on what your plan for updating the R and python tutorials are?

**Comment by TimVanMourik** [comment]
Your point in #7:

> From my point of view, I don't think I agree that the repository is clearer with the namings you suggest in #8 because the word tutorial was a very conscious choice! The goal is to orient people who aren't used to visiting a GitHub page to find a tutorial as quickly as possible.

I share your vision, and that's why I made an `examples` directory in the home directory of the project. If these work out of the box, I would say it is clear to everyone, beginner or pro, where the examples are. If you prefer the word `tutorials` instead of `examples`, I'm of course fine with that.

With respect to your other point: I wasn't finished yet, but what it probably comes down to is that I'll restructure here and there (also Python and R) files and let you and maintainers fix the references. Provided that you agree of course, because largely structure is a matter of taste.

**Comment by KirstieJane** [comment]
Coolio - I'll let the others weigh in on the restructure and return after that 😸

**Comment by TimVanMourik** [comment]
I merged the `refactoring` branch to this one, which was a probably a bad idea. It's not so clear now that the restructuring commits are rather minimal. All tutorial code is now moved to subfolders of `examples. All code that needs to be on the path at execution time is present in `~/MATLAB`, `~/R`, and `~/Python`. Where Python is a bit of an exception, as it needs to be pip installed. So instead I made a tiny Readme that says so.

#TODO for Python and R:
* Check if I moved things correctly
* Update links to example data and to output figures
* Update installation explanation

**Comment by KirstieJane** [comment]
Thanks @TimVanMourik. This still has `WIP` in the subject line so are you still working on this one? It probably makes sense to merge #10 first and then review this one, right?

Thanks for all the hard work!!

**Comment by TimVanMourik** [comment]
To me a PR is `WIP` as long as it is not ready to merge yet. Which it isn't as first the Python and R sections still need to be reviewed. But I'm not a Jupyter or R coder, so I would like to ask y'all to take it from here. 

Actually this one precedes #10, but I've been sloppy with branches so it really is my fault that that's not clear 🙄

**Comment by KirstieJane** [comment]
Gotcha. I've added the `help wanted` tag to make it easier to see that there's work that needs to be done....but not by you 😃

**Comment by KirstieJane** [comment]
Hi @micahgallen! @TimVanMourik has suggested a different layout for the github repository. It basically puts all the data in one place and then has different examples in another.

I think it probably makes sense to do it that way, but I know you're currently working on a harmonised tutorial. Ping me on some sort of messaging service when you have time and I can talk you through this structure if you'd like 👾

**Pull request merged**
